[target.x86_64-unknown-linux-gnu]
dockerfile = "./docker/Dockerfile.x86_64-unknown-linux-gnu"

[target.x86_64-pc-windows-gnu]
dockerfile = "./docker/Dockerfile.x86_64-pc-windows-gnu"

[target.aarch64-unknown-linux-gnu]
dockerfile = "./docker/Dockerfile.aarch64-unknown-linux-gnu"

[target.armv7-unknown-linux-gnueabihf]
dockerfile = "./docker/Dockerfile.armv7-unknown-linux-gnueabihf"

